version: '3.8'

services:
   auxdibot:
      container_name: auxdibot
      build:
         context: ./
         dockerfile: Dockerfile
         args:
            MONGO_URI: ${MONGO_URI}
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            DISCORD_BOT_CLIENT_ID: ${DISCORD_BOT_CLIENT_ID}
            DISCORD_INVITE_LINK: ${DISCORD_INVITE_LINK}
            BOT_HOMEPAGE: ${BOT_HOMEPAGE}
            BOT_STATUS_MESSAGE: ${BOT_STATUS_MESSAGE}
            AUTH_SECRET: ${AUTH_SECRET}
            SITE_URL: ${SITE_URL}
            YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
            HMAC_SECRET: ${HMAC_SECRET}
            TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
            TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
            DISCORD_OAUTH2_CLIENT_SECRET: ${DISCORD_OAUTH2_CLIENT_SECRET}
            DISCORD_OAUTH2_CALLBACK_URL: ${DISCORD_OAUTH2_CALLBACK_URL}
      image: auxdibot:latest
      env_file:
        - .env
      restart: always
      networks:
         - auxdibot
      ports:
         - 1080:1080
networks:
   auxdibot:
      external: true

      
