export enum LogType {
    "LOG_CHANNEL_CHANGED",
    "MUTE_ROLE_CHANGED",
    "WARN",
    "KICK",
    "MUTE",
    "BAN",
    "UNMUTE",
    "UNBAN",
    "MEMBER_JOIN",
    "MEMBER_LEAVE",
    "PUNISHMENT_EXPIRED",
    "PUNISHMENT_DELETED",
    "PERMISSION_CREATED",
    "PERMISSION_DELETED",
    "MESSAGE_EDITED",
    "MESSAGE_DELETED",
    "JOIN_LEAVE_CHANNEL_CHANGED",
    "JOIN_ROLE_ADDED",
    "JOIN_ROLE_REMOVED",
    "STICKY_ROLE_ADDED",
    "STICKY_ROLE_REMOVED",
    "REACTION_ROLE_ADDED",
    "REACTION_ROLE_REMOVED",
    "REACTION_ROLE_EDITED",
    "MASSROLE_GIVEN",
    "MASSROLE_TAKEN",
    "SUGGESTION_CREATED",
    "SUGGESTIONS_CHANNEL_CHANGED",
    "SUGGESTIONS_UPDATES_CHANNEL_CHANGED",
    "SUGGESTIONS_AUTO_DELETE_CHANGED",
    "SUGGESTIONS_THREAD_CREATION_CHANGED",
    "SUGGESTION_DELETED"
}

export const LogNames = {
    0: "🗒️ Log Channel Changed",
    1: "🎤 Mute Role Changed",
    2: "⚠ Warn",
    3: "🚷 Kick",
    4: "🔇 Mute",
    5: "🔨 Ban",
    6: "🔊 Unmute",
    7: "📥 Unban",
    8: "👋 Member Join",
    9: "🚶 Member Leave",
    10: "🗓️ Punishment Expired",
    11: "🗑️ Punishment Deleted",
    12: "✋ Permission Created",
    13: "🗑️ Permission Deleted",
    14: "🖊️ Message Edited",
    15: "🗙 Message Deleted",
    16: "📩 Join/Leave Channel Changed",
    17: "👋 Join Role Added",
    18: "👋 Join Role Removed",
    19: "📝 Sticky Role Added",
    20: "📝 Sticky Role Removed",
    21: "👈 Reaction Role Added",
    22: "👈 Reaction Role Removed",
    23: "👈 Reaction Role Edited",
    24: "🪪 Massrole Given",
    25: "🪪 Massrole Taken",
    26: "❓ Suggestion Created",
    27: "❓ Suggestions Channel Changed",
    28: "❓ Suggestions Updates Channel Changed",
    29: "❓ Suggestions Auto Delete Changed",
    30: "❓ Suggestions Thread Creation Changed",
    31: "❓ Suggestion Deleted",

}