enum Limits {
   ACTIVE_SUGGESTIONS_DEFAULT_LIMIT = 30,
   ACTIVE_PUNISHMENTS_DEFAULT_LIMIT = 50,
   ACTIVE_STARRED_MESSAGES_DEFAULT_LIMIT = 50,
   PERMISSION_OVERRIDES_DEFAULT_LIMIT = 30,
   LEVEL_REWARDS_DEFAULT_LIMIT = 10,
   SUGGESTIONS_REACTIONS_DEFAULT_LIMIT = 5,
   JOIN_ROLE_DEFAULT_LIMIT = 10,
   STICKY_ROLE_DEFAULT_LIMIT = 5,
   REACTION_ROLE_DEFAULT_LIMIT = 10,
   SCHEDULE_LIMIT = 5,
   LOGGING_LIMIT = 10,
   AUTOMOD_BLACKLIST_LIMIT = 50,
   AUTOMOD_EXCEPTION_LIMIT = 5,
}
export default Limits;
