enum Limits {
   ACTIVE_SUGGESTIONS_DEFAULT_LIMIT = 50,
   ACTIVE_PUNISHMENTS_DEFAULT_LIMIT = 100,
   ACTIVE_STARRED_MESSAGES_DEFAULT_LIMIT = 50,
   PERMISSION_OVERRIDES_DEFAULT_LIMIT = 20,
   LEVEL_REWARDS_DEFAULT_LIMIT = 10,
   SUGGESTIONS_REACTIONS_DEFAULT_LIMIT = 5,
   JOIN_ROLE_DEFAULT_LIMIT = 10,
   STICKY_ROLE_DEFAULT_LIMIT = 10,
   REACTION_ROLE_DEFAULT_LIMIT = 20,
   SCHEDULE_LIMIT = 10,
}
export default Limits;
